# Generated by Django 5.2.4 on 2025-08-08 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_image', models.URLField(blank=True, null=True)),
                ('diamonds', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-diamonds'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(max_length=100)),
                ('gift_image', models.URLField(blank=True, null=True)),
                ('gift_count', models.IntegerField(default=1)),
                ('diamonds', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='live.donator')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
